# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['bruno.avinint@gmail.com']
    delivery_whitelist:
        - '/@hotmail\.com$/'
